apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: custom-unitxt-eval
  namespace: lmeval-testing
spec:
  allowOnline: true
  allowCodeExecution: true
  
  # Using HuggingFace model for simplicity
  model: hf
  modelArgs:
    - name: pretrained
      value: google/flan-t5-small
  
  taskList:
    taskRecipes:
      - card:
          ref: my-custom-card        # Reference to custom card below
        template:
          ref: my-custom-template    # Reference to custom template below
    
    # Define custom components here
    custom:
      cards:
        - name: my-custom-card
          value: |
            {
              "__type__": "task_card",
              "loader": {
                "__type__": "load_hf",
                "path": "glue",
                "name": "wnli"
              },
              "preprocess_steps": [
                {
                  "__type__": "rename",
                  "field": "sentence1",
                  "to_field": "premise"
                },
                {
                  "__type__": "rename",
                  "field": "sentence2",
                  "to_field": "hypothesis"
                },
                {
                  "__type__": "map_instance_values",
                  "mappers": {
                    "label": {
                      "0": "no",
                      "1": "yes"
                    }
                  }
                },
                {
                  "__type__": "set",
                  "fields": {
                    "classes": ["yes", "no"]
                  }
                }
              ],
              "task": "tasks.classification.multi_class.relation"
            }
      
      templates:
        - name: my-custom-template
          value: |
            {
              "__type__": "input_output_template",
              "instruction": "Determine if the hypothesis follows from the premise. Answer only 'yes' or 'no'.",
              "input_format": "Premise: {premise}\nHypothesis: {hypothesis}",
              "output_format": "{label}",
              "target_prefix": "Answer: "
            }
  
  logSamples: true
  limit: "10"
  batchSize: "1"
