apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: custom-unitxt-eval-v4
  namespace: lmeval-testing
spec:
  allowOnline: true
  allowCodeExecution: true
  
  model: hf
  modelArgs:
    - name: pretrained
      value: google/flan-t5-small
  
  taskList:
    taskRecipes:
      - template:
          name: "templates.classification.multi_class.relation.default"
        card:
          custom: |
            {
              "__type__": "task_card",
              "loader": {
                "__type__": "load_hf",
                "path": "glue",
                "name": "wnli"
              },
              "preprocess_steps": [
                {
                  "__type__": "rename",
                  "field": "sentence1",
                  "to_field": "text_a"
                },
                {
                  "__type__": "rename",
                  "field": "sentence2",
                  "to_field": "text_b"
                },
                {
                  "__type__": "map_instance_values",
                  "mappers": {
                    "label": {
                      "0": "not entailment",
                      "1": "entailment"
                    }
                  }
                },
                {
                  "__type__": "set",
                  "fields": {
                    "classes": ["entailment", "not entailment"],
                    "text_a_type": "premise",
                    "text_b_type": "hypothesis",
                    "type_of_relation": "entailment"
                  }
                }
              ],
              "task": "tasks.classification.multi_class.relation"
            }
  
  logSamples: true
  limit: "10"
  batchSize: "1"
