apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: custom-local-success
  namespace: lmeval-testing
spec:
  allowOnline: true
  allowCodeExecution: true
  
  # Use locally deployed Qwen model
  model: local-completions
  modelArgs:
    - name: model
      value: "Qwen/Qwen3-0.6B"
    - name: base_url
      value: "http://openshift-ai-inference-openshift-ai-inference.openshift-ingress.svc.cluster.local:80/my-first-model/qwen3-0-6b/v1/completions"
    - name: tokenizer
      value: Qwen/Qwen2.5-0.5B
    - name: num_concurrent
      value: "1"
    - name: max_retries
      value: "3"
    - name: tokenized_requests
      value: "False"
  
  taskList:
    taskRecipes:
      - template:
          name: "templates.classification.multi_class.relation.default"
        card:
          custom: |
            {
              "__type__": "task_card",
              "loader": {
                "__type__": "load_hf",
                "path": "glue",
                "name": "wnli"
              },
              "preprocess_steps": [
                {"__type__": "rename", "field": "sentence1", "to_field": "text_a"},
                {"__type__": "rename", "field": "sentence2", "to_field": "text_b"},
                {"__type__": "map_instance_values", "mappers": {"label": {"0": "not entailment", "1": "entailment", "-1": "unknown"}}},
                {"__type__": "set", "fields": {"classes": ["entailment", "not entailment", "unknown"], "text_a_type": "premise", "text_b_type": "hypothesis", "type_of_relation": "entailment"}}
              ],
              "task": "tasks.classification.multi_class.relation"
            }
        numDemos: 3
        demosPoolSize: 50
  
  logSamples: true
  limit: "10"
  batchSize: "1"
