apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: multi-task-eval
  namespace: lmeval-testing
spec:
  allowOnline: true
  allowCodeExecution: true

  # Using local-completions (supports ALL task types)
  model: local-completions
  
  modelArgs:
    - name: model
      value: "Qwen/Qwen3-0.6B"
    - name: base_url
      value: "http://openshift-ai-inference-openshift-ai-inference.openshift-ingress.svc.cluster.local:80/my-first-model/qwen3-0-6b/v1/completions"
    - name: tokenizer
      value: Qwen/Qwen2.5-0.5B
    - name: num_concurrent
      value: "1"
    - name: max_retries
      value: "3"
    - name: tokenized_requests
      value: "False"

  # Multiple task types to test
  taskList:
    taskNames:
      # Loglikelihood tasks (multiple choice)
      - arc_challenge      # Harder science questions
      - hellaswag          # Common sense reasoning
      - winogrande         # Pronoun resolution
      # Generation tasks
      - lambada_openai     # Story completion (last word prediction)

  limit: "5"
  batchSize: "1"
  logSamples: true
