apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: local-chat-gen
  namespace: lmeval-testing
spec:
  allowOnline: true
  allowCodeExecution: true

  # Model - Chat Completions
  model: local-chat-completions
  
  modelArgs:
    - name: model
      value: "Qwen/Qwen3-0.6B"
    - name: base_url
      value: "http://openshift-ai-inference-openshift-ai-inference.openshift-ingress.svc.cluster.local:80/my-first-model/qwen3-0-6b/v1/chat/completions"
    - name: tokenizer
      value: Qwen/Qwen3-0.6B
    - name: num_concurrent
      value: "1"
    - name: max_retries
      value: "3"

  # Enable chat template
  chatTemplate:
    enabled: true

  # GENERATION-BASED tasks (not loglikelihood)
  taskList:
    taskNames:
      - gsm8k
      - truthfulqa_gen

  limit: "5"
  batchSize: "1"
  logSamples: true
