apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: local-model-eval-v2
  namespace: lmeval-testing
spec:
  # Security
  allowOnline: true
  allowCodeExecution: true
  
  # Model - Use Gateway URL
  model: local-completions
  modelArgs:
    - name: model
      value: qwen3-0-6b
    - name: base_url
      value: "https://aed7822c4ec88495fa795e5c47c2d24f-1452512295.ap-southeast-1.elb.amazonaws.com/my-first-model/qwen3-0-6b/v1/completions"
    - name: tokenizer
      value: Qwen/Qwen2.5-0.5B
    - name: num_concurrent
      value: "1"
    - name: max_retries
      value: "3"
    - name: tokenized_requests
      value: "False"
  
  # Task - Simple evaluation
  taskList:
    taskNames:
      - arc_easy
  
  # Limit samples for quick test
  limit: "10"
  
  # Logging
  logSamples: true
  batchSize: "1"
