# Phase 4: Local Model Evaluation using local-completions
# This YAML evaluates a model deployed on OpenShift AI using the internal gateway
#
# Key Points:
# - Uses HTTP via internal gateway (no SSL issues)
# - Model is already running on OpenShift (qwen3-0-6b)
# - LMEvalJob sends requests to the model's API endpoint
#
# How to find your model's URL:
# 1. oc get svc -n openshift-ingress | grep openshift-ai-inference
# 2. Use: http://<gateway-svc>.<namespace>.svc.cluster.local:80/<model-namespace>/<model-name>/v1/completions

apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: local-model-eval
  namespace: lmeval-testing
spec:
  # ═══════════════════════════════════════════════════════════════════
  # SECURITY SETTINGS
  # ═══════════════════════════════════════════════════════════════════
  allowOnline: true              # Needed to download tokenizer from HuggingFace
  allowCodeExecution: true       # Some tasks need this

  # ═══════════════════════════════════════════════════════════════════
  # MODEL CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════
  model: local-completions       # Use local server (not HuggingFace download)
  
  modelArgs:
    # Model name (must match what the server reports)
    - name: model
      value: "Qwen/Qwen3-0.6B"
    
    # Internal gateway URL (HTTP, no SSL)
    # Format: http://<gateway-svc>.<gateway-ns>.svc.cluster.local:80/<model-ns>/<model-name>/v1/completions
    - name: base_url
      value: "http://openshift-ai-inference-openshift-ai-inference.openshift-ingress.svc.cluster.local:80/my-first-model/qwen3-0-6b/v1/completions"
    
    # Tokenizer from HuggingFace (for token counting)
    - name: tokenizer
      value: Qwen/Qwen2.5-0.5B
    
    # Concurrency settings
    - name: num_concurrent
      value: "1"
    - name: max_retries
      value: "3"
    - name: tokenized_requests
      value: "False"

  # ═══════════════════════════════════════════════════════════════════
  # TASK CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════
  taskList:
    taskNames:
      - arc_easy                 # Grade-school science questions

  # ═══════════════════════════════════════════════════════════════════
  # EVALUATION SETTINGS
  # ═══════════════════════════════════════════════════════════════════
  limit: "10"                    # Limit to 10 samples for quick test
  batchSize: "1"                 # Process 1 sample at a time
  logSamples: true               # Save detailed logs
